<a href="https://colab.research.google.com/github/ramya1807/Hospital-Playlist/blob/main/Data_Visualization_for_Meeting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Naive Bayes

In [ ]:
#Model Naive Baiyes for predicting trauma or indiv mental health indicators

In [2]:
import pandas as pd
data = pd.read_csv('data_cleaned2.csv')

In [3]:
data.columns

Index(['gender', 'age', 'amount_music', 'life_enjoyment', 'resilience',
       'balanced_life', 'emotional_flex', 'self_actualization', 'trauma',
       'total_health', 'health_categorical', 'energy', 'dance', 'liveness',
       'valence', 'tempo', 'instrumental', 'acoustic', 'popularity', 'genres'],
      dtype='object')

##trauma

In [4]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['trauma', # y
             'gender', 
             'age', 
             'amount_music',
             'life_enjoyment', 
             'resilience', 
             'balanced_life', 
             'emotional_flex', 
             'self_actualization',
             'health_categorical',
             'total_health',
             'genres'],
            axis = 1),
            data['trauma'], # y to be predicted
            test_size=0.3,
            random_state=0) 

from sklearn.preprocessing import StandardScaler

# define a new scaler: 
x_scaler = StandardScaler()

# fit the normalization on the training set: 
x_scaler.fit(X_train)

# then create new and normalized training/test sets: 
X_train_norm = x_scaler.transform(X_train)
X_test_norm = x_scaler.transform(X_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt


def evaluate_on_training_set(y_test, y_pred):
  # Calculate AUC
  #print("AUC is: ", roc_auc_score(y_test, y_pred))
  
  # print out recall and precision
  print(classification_report(y_test, y_pred))
  
  # print out confusion matrix
  print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))


In [21]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB() # Define the model with parameters

In [22]:
model.fit(X_train_norm, y_train) # Training the model

y_pred = model.predict(X_test_norm) # Predicting labels for our test set using trained model
evaluate_on_training_set(y_test, y_pred) #evaluate our model using newly defined function

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.10      0.09      0.10        11
           2       0.05      0.04      0.04        28
           3       0.30      0.31      0.31        48
           4       0.23      0.47      0.31        36
           5       0.00      0.00      0.00        26
           6       0.00      0.00      0.00        12

    accuracy                           0.20       166
   macro avg       0.10      0.13      0.11       166
weighted avg       0.15      0.20      0.17       166

Confusion Matrix: 
 [[ 0  0  1  0  4  0  0]
 [ 0  1  0  4  6  0  0]
 [ 0  2  1 10 12  2  1]
 [ 0  3  8 15 20  1  1]
 [ 1  0  9  6 17  2  1]
 [ 0  2  1 12 11  0  0]
 [ 1  2  1  3  5  0  0]]


##life enjoyment

In [23]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['life_enjoyment', # y
             'gender', 
             'age', 
             'amount_music',
             'resilience', 
             'balanced_life', 
             'emotional_flex', 
             'self_actualization',
             'trauma',
             'health_categorical',
             'total_health',
             'genres'],
            axis = 1),
            data['life_enjoyment'], # y to be predicted
            test_size=0.3,
            random_state=0) 

from sklearn.preprocessing import StandardScaler

# define a new scaler: 
x_scaler = StandardScaler()

# fit the normalization on the training set: 
x_scaler.fit(X_train)

# then create new and normalized training/test sets: 
X_train_norm = x_scaler.transform(X_train)
X_test_norm = x_scaler.transform(X_test)

In [24]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB() # Define the model with parameters

model.fit(X_train_norm, y_train) # Training the model

y_pred = model.predict(X_test_norm) # Predicting labels for our test set using trained model
evaluate_on_training_set(y_test, y_pred) #evaluate our model using newly defined function

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.10      0.09      0.10        11
           2       0.05      0.04      0.04        28
           3       0.30      0.31      0.31        48
           4       0.23      0.47      0.31        36
           5       0.00      0.00      0.00        26
           6       0.00      0.00      0.00        12

    accuracy                           0.20       166
   macro avg       0.10      0.13      0.11       166
weighted avg       0.15      0.20      0.17       166

Confusion Matrix: 
 [[ 0  0  1  0  4  0  0]
 [ 0  1  0  4  6  0  0]
 [ 0  2  1 10 12  2  1]
 [ 0  3  8 15 20  1  1]
 [ 1  0  9  6 17  2  1]
 [ 0  2  1 12 11  0  0]
 [ 1  2  1  3  5  0  0]]


##resilience

In [25]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['resilience', # y
             'gender', 
             'age', 
             'amount_music',
             'life_enjoyment', 
             'balanced_life', 
             'emotional_flex', 
             'self_actualization',
             'trauma',
             'health_categorical',
             'total_health',
             'genres'],
            axis = 1),
            data['resilience'], # y to be predicted
            test_size=0.3,
            random_state=0) 

from sklearn.preprocessing import StandardScaler

# define a new scaler: 
x_scaler = StandardScaler()

# fit the normalization on the training set: 
x_scaler.fit(X_train)

# then create new and normalized training/test sets: 
X_train_norm = x_scaler.transform(X_train)
X_test_norm = x_scaler.transform(X_test)

In [26]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB() # Define the model with parameters

model.fit(X_train_norm, y_train) # Training the model

y_pred = model.predict(X_test_norm) # Predicting labels for our test set using trained model
evaluate_on_training_set(y_test, y_pred) #evaluate our model using newly defined function

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00        18
           3       0.08      0.04      0.06        23
           4       0.30      0.68      0.42        47
           5       0.32      0.18      0.23        49
           6       0.00      0.00      0.00        26

    accuracy                           0.25       166
   macro avg       0.10      0.13      0.10       166
weighted avg       0.19      0.25      0.19       166

Confusion Matrix: 
 [[ 0  0  0  1  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  2 13  3  0]
 [ 1  0  4  1 10  7  0]
 [ 0  0  5  2 32  8  0]
 [ 2  2  3  5 28  9  0]
 [ 0  0  1  2 22  1  0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##balanced life

In [27]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['balanced_life', # y
             'gender', 
             'age', 
             'amount_music',
             'life_enjoyment', 
             'resilience', 
             'emotional_flex', 
             'self_actualization',
             'trauma',
             'health_categorical',
             'total_health',
             'genres'],
            axis = 1),
            data['balanced_life'], # y to be predicted
            test_size=0.3,
            random_state=0) 

from sklearn.preprocessing import StandardScaler

# define a new scaler: 
x_scaler = StandardScaler()

# fit the normalization on the training set: 
x_scaler.fit(X_train)

# then create new and normalized training/test sets: 
X_train_norm = x_scaler.transform(X_train)
X_test_norm = x_scaler.transform(X_test)

In [28]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB() # Define the model with parameters

model.fit(X_train_norm, y_train) # Training the model

y_pred = model.predict(X_test_norm) # Predicting labels for our test set using trained model
evaluate_on_training_set(y_test, y_pred) #evaluate our model using newly defined function

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         6
           2       0.33      0.11      0.17        36
           3       0.10      0.06      0.07        36
           4       0.23      0.28      0.25        32
           5       0.23      0.50      0.32        38
           6       0.00      0.00      0.00        16

    accuracy                           0.20       166
   macro avg       0.13      0.14      0.12       166
weighted avg       0.19      0.20      0.17       166

Confusion Matrix: 
 [[ 0  0  1  0  1  0  0]
 [ 0  0  0  4  1  1  0]
 [ 2  2  4  2 11 15  0]
 [ 0  2  4  2  6 21  1]
 [ 0  2  1  4  9 15  1]
 [ 1  0  2  7  9 19  0]
 [ 0  2  0  1  3 10  0]]


##emotional flexibility

In [29]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['emotional_flex', # y
             'gender', 
             'age', 
             'amount_music',
             'life_enjoyment', 
             'resilience', 
             'balanced_life', 
             'self_actualization',
             'trauma',
             'health_categorical',
             'total_health',
             'genres'],
            axis = 1),
            data['emotional_flex'], # y to be predicted
            test_size=0.3,
            random_state=0) 

from sklearn.preprocessing import StandardScaler

# define a new scaler: 
x_scaler = StandardScaler()

# fit the normalization on the training set: 
x_scaler.fit(X_train)

# then create new and normalized training/test sets: 
X_train_norm = x_scaler.transform(X_train)
X_test_norm = x_scaler.transform(X_test)

In [30]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB() # Define the model with parameters

model.fit(X_train_norm, y_train) # Training the model

y_pred = model.predict(X_test_norm) # Predicting labels for our test set using trained model
evaluate_on_training_set(y_test, y_pred) #evaluate our model using newly defined function

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.05      0.27      0.08        11
           2       0.22      0.07      0.11        28
           3       0.16      0.25      0.20        24
           4       0.17      0.11      0.13        38
           5       0.15      0.11      0.13        36
           6       0.50      0.12      0.20        24

    accuracy                           0.13       166
   macro avg       0.18      0.13      0.12       166
weighted avg       0.21      0.13      0.14       166

Confusion Matrix: 
 [[ 0  1  0  2  1  1  0]
 [ 0  3  2  2  2  2  0]
 [ 0  8  2  3  5  8  2]
 [ 0 10  2  6  4  2  0]
 [ 0 14  0 13  4  7  0]
 [ 1 16  2  8  4  4  1]
 [ 0 11  1  3  3  3  3]]


##self-actualization

In [31]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['self_actualization', # y
             'gender', 
             'age', 
             'amount_music',
             'life_enjoyment', 
             'resilience', 
             'balanced_life', 
             'emotional_flex',
             'trauma',
             'health_categorical',
             'total_health',
             'genres'],
            axis = 1),
            data['self_actualization'], # y to be predicted
            test_size=0.3,
            random_state=0) 

from sklearn.preprocessing import StandardScaler

# define a new scaler: 
x_scaler = StandardScaler()

# fit the normalization on the training set: 
x_scaler.fit(X_train)

# then create new and normalized training/test sets: 
X_train_norm = x_scaler.transform(X_train)
X_test_norm = x_scaler.transform(X_test)

In [32]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB() # Define the model with parameters

model.fit(X_train_norm, y_train) # Training the model

y_pred = model.predict(X_test_norm) # Predicting labels for our test set using trained model
evaluate_on_training_set(y_test, y_pred) #evaluate our model using newly defined function

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.00      0.00      0.00         7
           2       0.08      0.92      0.15        12
           3       0.00      0.00      0.00        20
           4       0.00      0.00      0.00        39
           5       0.17      0.02      0.04        47
           6       0.20      0.03      0.05        38

    accuracy                           0.08       166
   macro avg       0.06      0.14      0.03       166
weighted avg       0.10      0.08      0.03       166

Confusion Matrix: 
 [[ 0  0  3  0  0  0  0]
 [ 0  0  6  0  0  1  0]
 [ 0  0 11  0  1  0  0]
 [ 0  1 17  0  1  1  0]
 [ 1  4 30  0  0  1  3]
 [ 0  3 37  0  5  1  1]
 [ 0  0 30  0  5  2  1]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#Linear Regression

In [ ]:
#Regression - for predicting total health score or individual mental health indicators

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

##total health

In [37]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['total_health', # y
             'gender', 
             'age', 
             'amount_music',
             'life_enjoyment', 
             'resilience', 
             'balanced_life', 
             'emotional_flex', 
             'self_actualization',
             'health_categorical',
             'trauma',
             'genres'],
            axis = 1),
            data['total_health'], # y to be predicted
            test_size=0.3,
            random_state=0) 


regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)
mean_squared_error(y_test, y_pred)

27.630289967550237

##life enjoyment

In [38]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['life_enjoyment', # y
             'gender', 
             'age', 
             'amount_music',
             'total_health', 
             'resilience', 
             'balanced_life', 
             'emotional_flex', 
             'self_actualization',
             'health_categorical',
             'trauma',
             'genres'],
            axis = 1),
            data['life_enjoyment'], # y to be predicted
            test_size=0.3,
            random_state=0) 


regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)
mean_squared_error(y_test, y_pred)

2.0826499000926924

##resilience

In [39]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['resilience', # y
             'gender', 
             'age', 
             'amount_music',
             'total_health', 
             'life_enjoyment', 
             'balanced_life', 
             'emotional_flex', 
             'self_actualization',
             'health_categorical',
             'trauma',
             'genres'],
            axis = 1),
            data['resilience'], # y to be predicted
            test_size=0.3,
            random_state=0) 


regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)
mean_squared_error(y_test, y_pred)

1.8119926583482817

##balanced life

In [40]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['balanced_life', # y
             'gender', 
             'age', 
             'amount_music',
             'total_health', 
             'life_enjoyment', 
             'resilience', 
             'emotional_flex', 
             'self_actualization',
             'health_categorical',
             'trauma',
             'genres'],
            axis = 1),
            data['balanced_life'], # y to be predicted
            test_size=0.3,
            random_state=0) 


regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)
mean_squared_error(y_test, y_pred)

2.0442350149360973

##emotional flexibility

In [41]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['emotional_flex', # y
             'gender', 
             'age', 
             'amount_music',
             'total_health', 
             'life_enjoyment', 
             'resilience', 
             'balanced_life', 
             'self_actualization',
             'health_categorical',
             'trauma',
             'genres'],
            axis = 1),
            data['emotional_flex'], # y to be predicted
            test_size=0.3,
            random_state=0) 


regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)
mean_squared_error(y_test, y_pred)

2.7217907433560047

##self-actualization

In [42]:
# training and test split
from sklearn.model_selection import train_test_split

# data = pd.get_dummies(data, drop_first=True)
# We split the data up into a test set and a training set, 30 - 70 %
# train_test_split
# First argument: x data is all data without class column
# Second argument:  this is the class label column
# Random state = 0: ensures the train and test splitting is deterministic. 

X_train, X_test, y_train, y_test = train_test_split(data.drop(['self_actualization', # y
             'gender', 
             'age', 
             'amount_music',
             'total_health', 
             'life_enjoyment', 
             'resilience', 
             'balanced_life', 
             'emotional_flex',
             'health_categorical',
             'trauma',
             'genres'],
            axis = 1),
            data['self_actualization'], # y to be predicted
            test_size=0.3,
            random_state=0) 


regr = LinearRegression()
regr.fit(X_train,y_train)
y_pred = regr.predict(X_test)
mean_squared_error(y_test, y_pred)

2.2145310870810677